Update documentation
snogcel/bitcore-payment-protocol pull request #15
Opened 2018-12-29 12:16 UTC by nmarley

* Update package author
* Cleanup README a bit and add publish instructions to README
* Dashify documentation and remove bower references

Based on #13, so that should be merged first

2019-01-03 16:13 UTC, Cofresi requested changes
use the @dashevo namespace npm packages

2019-01-03 16:13 UTC, Cofresi commented on README.md
>  npm install dashcore-payment-protocol
```npm install @dashevo/dashcore-lib
npm install @dashevo/dashcore-payment-protocol```

2019-01-03 16:16 UTC, Cofresi requested changes
same as above

2019-01-03 16:16 UTC, Cofresi commented on docs/index.md
>  ```
same as above
```
npm install @dashevo/dashcore-lib
npm install @dashevo/dashcore-payment-protocol
```

2019-01-03 16:16 UTC, Cofresi commented on docs/index.md
`var PaymentProtocol = require('@dashevo/dashcore-payment-protocol');`

2019-01-04 00:03 UTC, nmarley commented on README.md
>  npm install dashcore-payment-protocol
Nice catch! Should be fixed in both files now.

2019-01-04 00:27 UTC, Cofresi approved these changes

2019-01-04 00:27 UTC, merged