Move NPM to scopped org
snogcel/bitcore-payment-protocol pull request #3
Opened 2018-04-08 16:53 UTC by Alex-Werner

2018-04-08 18:01 UTC, akfranco requested changes

2018-04-08 18:01 UTC, KamuelaFranco commented on package.json
> +    "url": "https://github.com/dahevo/bitcore-payment-protocol-dash.git"
Small typo

2018-04-08 18:31 UTC, Alex-Werner commented on package.json
> +    "url": "https://github.com/dahevo/bitcore-payment-protocol-dash.git"
Thanks  a lot ! Fixed !

2018-04-09 10:55 UTC, akfranco approved these changes

2018-04-09 10:55 UTC, merged